export const ErrorCode = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  USER_EXISTED: "USER_EXISTED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  ACCESS_TOKEN_REQUIRED: "ACCESS_TOKEN_REQUIRED",
  OTP_REQUIRED: "OTP_REQUIRED",
} as const;
